# Generated by Django 5.1.6 on 2025-03-01 03:20
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('Tech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amiibo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('is_owned', models.BooleanField(default=True)),
                ('condition_status', models.CharField(
                    choices=[('box', 'BOX'), ('not_box', 'Not in BOX')],
                    default='not_box',
                    max_length=15
                )),
            ],
        ),
    ]
